server {
    listen 80;
    server_name edcnitd.co.in www.edcnitd.co.in;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


