services:
  django:
    build: .
    container_name: django
    restart: unless-stopped
    volumes:
      - ./website/db.sqlite3:/app/website/db.sqlite3
      - static_volume:/app/website/staticfiles
      - media_volume:/app/website/media
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=website.settings
      - DJANGO_ENV=production
    stdin_open: true
    tty: true

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      - SERVER_NAME=edcnitd.co.in
    volumes:
      - static_volume:/app/website/staticfiles
      - media_volume:/app/website/media
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    profiles:
      - certs

volumes:
  static_volume:
  media_volume:
  certbot_certs:
  certbot_webroot: