server {
    listen 443 ssl;
    http2 on;
    server_name edcnitd.co.in www.edcnitd.co.in;

    ssl_certificate /etc/letsencrypt/live/edcnitd.co.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/edcnitd.co.in/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/edcnitd.co.in/chain.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';
    ssl_prefer_server_ciphers off;

    ssl_dhparam /etc/ssl/certs/dhparam.pem;

    client_max_body_size 20M;

    location /static/ {
        alias /static/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        alias /media/;
        access_log off;
        expires 30d;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
    }
}

server {
    listen 80;
    server_name edcnitd.co.in www.edcnitd.co.in;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
